2024-11-25 10:25:00,479 | INFO | "test_challenge" выполнен успешно
2024-11-25 10:25:00,479 | WARNING | Неверный тип данных для объекта Runner
Имя может быть только строкой, передано int
2024-11-25 10:25:00,480 | WARNING | Traceback (most recent call last):
  File "E:\project_for_python\module_12\tests_12_4.py", line 88, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "E:\project_for_python\module_12\tests_12_4.py", line 20, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int

2024-11-25 10:25:00,481 | WARNING | Неверная скорость для Runner
Скорость не может быть отрицательной, сейчас -5
2024-11-25 10:25:00,483 | WARNING | Traceback (most recent call last):
  File "E:\project_for_python\module_12\tests_12_4.py", line 77, in test_walk
    runner = Runner("Вася", -5)
             ^^^^^^^^^^^^^^^^^^
  File "E:\project_for_python\module_12\tests_12_4.py", line 25, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

